name: Check Kubernetes Pod Status

on:
 push:
  branches:
   - main


jobs:
 check-pod-status:
  runs-on: self-hosted

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Check pod status
     run: |
       kubectl get pods --namespace fubuntu-default
