name: Check Kubernetes Pod Status

on: [push , workflow_dispatch]

jobs:
 check-pod-status:
  runs-on: ubuntu-latest
  outputs:
   bads: ${{ steps.check.outputs.FAILED }}
   fall: ${{ steps.connect.outputs.FILL }}
  steps:
    - uses: actions/checkout@v2
    - name: connect via proxy and execute commands
      id: connect
      env:
       fall: ${{ steps.connect.outputs.FILL }}
      uses: appleboy/ssh-action@v1.1.0
      with:
        proxy_host: ${{ secrets.PROXY_IP }}
        proxy_port: ${{ secrets.PROXY_PORT }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_password: ${{ secrets.PROXY_PASS }}
        host: ${{ secrets.CLUSTER_IP }}
        port: ${{ secrets.CLUSTER_PORT }}
        username: ${{ secrets.CLUSTER_USER }}
        password: ${{ secrets.CLUSTER_PASS }}
        script: |
         kubectl get pods -A > output.log
         echo "FALL=$(kubectl get pods -A | awk 'NR!=1 {print $4}' | grep -v 'Running' | wc -l)"
         FILL="$(kubectl get pods -A | awk 'NR!=1 {print $4}' | grep -v 'Running' | wc -l)"
         echo "FILL=$FILL" >> "$env:GITHUB_ENV"
    - name: check
      id: check
      env:
       fall: ${{ steps.connect.outputs.FILL }}
       bads: ${{ steps.check.outputs.FAILED }}
      run: |
         bad=$(echo "${{ env.fall }}")
         if [[ $bad -eq 0 ]]
         then
         echo "FAILED=FALSE" > "$GITHUB_OUTPUT"
         else
         echo "FAILED=TRUE" > "$GITHUB_OUTPUT"
         fi
 check:
  runs-on: ubuntu-latest
  needs: check-pod-status
  steps:
   - env:
      out1: ${{ needs.check-pod-status.outputs.bads }}
     run: echo "$out1"

 notification:
    needs: check-pod-status
    runs-on: ubuntu-latest
    if: needs.check-pod-status.outputs.bads == 'TRUE'
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: project
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: "Cluster has bad pod"
        SLACK_TITLE: K8s status
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
